[dev]
  port = 3333 # Port that the dev server will be listening on
  functionsPort = 44444 # port for functions server
  publish = "functions" 

[build]
  functions = "functions"

[[headers]]
# Define which paths this specific [[headers]] block will cover.
    for = "/*"
        [headers.values]
        Access-Control-Allow-Origin = "*"